# Generated by Django 3.0 on 2023-09-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='product_name')),
                ('srt_desc', models.CharField(max_length=288, verbose_name='short_description')),
                ('desc', models.TextField(verbose_name='html')),
            ],
        ),
    ]
